controller_list:
  - name: fake_MyRightArm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_MyLeftArm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint8
      - joint9
      - joint10
      - joint11
      - joint12
      - joint13
      - joint14
initial:  # Define initial robot poses per group
  - group: MyRightArm
    pose: home
  - group: MyLeftArm
    pose: home