controller_list:
  - name: fake_leftarm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint8
      - joint9
      - joint10
      - joint11
      - joint12
      - joint13
      - joint14
  - name: fake_rightarm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses per group
  - group: leftarm
    pose: home
  - group: rightarm
    pose: home