leftarm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint8
    - joint9
    - joint10
    - joint11
    - joint12
    - joint13
    - joint14
  gains:
    joint8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
rightarm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
  gains:
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1