controller_list:
  - name: leftarm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint8
      - joint9
      - joint10
      - joint11
      - joint12
      - joint13
      - joint14
  - name: rightarm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7